### ISSUE TITLE
[QUESTION] - Show All Usernames

### ISSUE THREAD

**Issue by maclacerda** [AdamBCo/ABCAutoCompleteTextView#4]
Hello,

How do I display all usernames by typing only "@" ???

Is this possible?

Thanks

**Comment by hfzwhd** [comment]
hi, figured out yet? mind to share?

**Comment by AdamBCo** [comment]
Sorry for the late reply on this issue! 

At the moment there is no way to display all usernames, so it's a feature I'll have to implement.

Since the textView is an autocompleting text view, you'll need to enter at least 1 character for it to work properly.

I hope this helps.
